// Folgender Code wirft einen ReferenceError
try{
    meineLieblingsFunktion();
} catch(error) {
    console.error("ein Fehler ist aufgetreten:", error.message);
}
